name: Commit Checks
on:
  push:
    branches:
      - main
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 19
        cache: 'yarn'

    - name: Install deps (for eslint plugins)
      run: yarn

    - name: ESLint
      run: yarn lint

    - name: Test compiliation
      run: yarn build:noEmit

    - name: Unit tests
      run: yarn test:unit

    - name: e2e tests
      run: yarn test:e2e